// Mocks generated by Mockito 5.4.4 from annotations
// in sut_smart_bus/test/test_mode_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i9;
import 'package:sut_smart_bus/models/bus.dart' as _i6;
import 'package:sut_smart_bus/models/route_model.dart' as _i7;
import 'package:sut_smart_bus/providers/data_provider.dart' as _i2;
import 'package:sut_smart_bus/services/api_service.dart' as _i5;
import 'package:sut_smart_bus/services/mqtt_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0 extends _i1.SmartFake implements _i2.DataState {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MqttService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMqttService extends _i1.Mock implements _i3.MqttService {
  MockMqttService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onMessage(_i3.MqttMessageCallback? _onMessage) => super.noSuchMethod(
        Invocation.setter(
          #onMessage,
          _onMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isCamCountSubscribed => (super.noSuchMethod(
        Invocation.getter(#isCamCountSubscribed),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribeToCamCount(_i3.CamCountCallback? onCount) => super.noSuchMethod(
        Invocation.method(
          #subscribeToCamCount,
          [onCount],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeFromCamCount() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromCamCount,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i6.Bus>> fetchBuses() => (super.noSuchMethod(
        Invocation.method(
          #fetchBuses,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Bus>>.value(<_i6.Bus>[]),
      ) as _i4.Future<List<_i6.Bus>>);

  @override
  _i4.Future<int?> fetchPassengerCount() => (super.noSuchMethod(
        Invocation.method(
          #fetchPassengerCount,
          [],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<List<_i7.BusRoute>> fetchRoutes() => (super.noSuchMethod(
        Invocation.method(
          #fetchRoutes,
          [],
        ),
        returnValue: _i4.Future<List<_i7.BusRoute>>.value(<_i7.BusRoute>[]),
      ) as _i4.Future<List<_i7.BusRoute>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchRouteList() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRouteList,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<_i7.BusRoute?> fetchRoute(String? routeId) => (super.noSuchMethod(
        Invocation.method(
          #fetchRoute,
          [routeId],
        ),
        returnValue: _i4.Future<_i7.BusRoute?>.value(),
      ) as _i4.Future<_i7.BusRoute?>);

  @override
  _i4.Future<bool> syncRoute(_i7.BusRoute? route) => (super.noSuchMethod(
        Invocation.method(
          #syncRoute,
          [route],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteRoute(String? routeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoute,
          [routeId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> createBus(
    String? mac,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBus,
          [
            mac,
            name,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateBus(
    String? mac,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBus,
          [
            mac,
            name,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteBus(String? mac) => (super.noSuchMethod(
        Invocation.method(
          #deleteBus,
          [mac],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> fetchBusRouteMappings(int? localVersion) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBusRouteMappings,
          [localVersion],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchHeatmapData(
          {String? timeRange = r'1h'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchHeatmapData,
          [],
          {#timeRange: timeRange},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> sendFakeLocation(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFakeLocation,
          [data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFakeLocation(String? busId) => (super.noSuchMethod(
        Invocation.method(
          #deleteFakeLocation,
          [busId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchPMZones() => (super.noSuchMethod(
        Invocation.method(
          #fetchPMZones,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> createPMZone(Map<String, dynamic>? zoneData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPMZone,
          [zoneData],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updatePMZone(
    String? zoneId,
    Map<String, dynamic>? zoneData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePMZone,
          [
            zoneId,
            zoneData,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deletePMZone(String? zoneId) => (super.noSuchMethod(
        Invocation.method(
          #deletePMZone,
          [zoneId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> submitFeedback(
    String? name,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitFeedback,
          [
            name,
            message,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> fetchSystemInfo() => (super.noSuchMethod(
        Invocation.method(
          #fetchSystemInfo,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> checkHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHealth,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [DataNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataNotifier extends _i1.Mock implements _i2.DataNotifier {
  MockDataNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i8.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.DataState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.DataState>.empty(),
      ) as _i4.Stream<_i2.DataState>);

  @override
  _i2.DataState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDataState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.DataState);

  @override
  set state(_i2.DataState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.DataState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeDataState_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.DataState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> refreshBuses() => (super.noSuchMethod(
        Invocation.method(
          #refreshBuses,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void handleMqttMessage(
    String? topic,
    Map<String, dynamic>? data,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleMqttMessage,
          [
            topic,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i2.DataState? old,
    _i2.DataState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.RemoveListener addListener(
    _i9.Listener<_i2.DataState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i8.RemoveListener);
}
