// Mocks generated by Mockito 5.4.4 from annotations
// in sut_smart_bus/test/test_mode_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mqtt_client/mqtt_client.dart' as _i4;
import 'package:sut_smart_bus/services/mqtt_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MqttService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMqttService extends _i1.Mock implements _i2.MqttService {
  MockMqttService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onMessage(_i2.MqttMessageCallback? _onMessage) => super.noSuchMethod(
        Invocation.setter(
          #onMessage,
          _onMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Stream<_i4.MqttConnectionState> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i3.Stream<_i4.MqttConnectionState>.empty(),
      ) as _i3.Stream<_i4.MqttConnectionState>);

  @override
  _i4.MqttConnectionState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i4.MqttConnectionState.disconnecting,
      ) as _i4.MqttConnectionState);

  @override
  bool get isCamCountSubscribed => (super.noSuchMethod(
        Invocation.getter(#isCamCountSubscribed),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribeToCamCount(_i2.CamCountCallback? onCount) => super.noSuchMethod(
        Invocation.method(
          #subscribeToCamCount,
          [onCount],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeFromCamCount() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromCamCount,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
