// Mocks generated by Mockito 5.4.4 from annotations
// in sut_smart_bus/test/test_mode_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i6;
import 'package:sut_smart_bus/providers/simulation_provider.dart' as _i2;
import 'package:sut_smart_bus/services/mqtt_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSimulationState_0 extends _i1.SmartFake
    implements _i2.SimulationState {
  _FakeSimulationState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MqttService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMqttService extends _i1.Mock implements _i3.MqttService {
  MockMqttService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onMessage(_i3.MqttMessageCallback? _onMessage) => super.noSuchMethod(
        Invocation.setter(
          #onMessage,
          _onMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isCamCountSubscribed => (super.noSuchMethod(
        Invocation.getter(#isCamCountSubscribed),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribeToCamCount(_i3.CamCountCallback? onCount) => super.noSuchMethod(
        Invocation.method(
          #subscribeToCamCount,
          [onCount],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeFromCamCount() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromCamCount,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SimulationNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSimulationNotifier extends _i1.Mock
    implements _i2.SimulationNotifier {
  MockSimulationNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i5.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.SimulationState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.SimulationState>.empty(),
      ) as _i4.Stream<_i2.SimulationState>);

  @override
  _i2.SimulationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSimulationState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.SimulationState);

  @override
  set state(_i2.SimulationState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SimulationState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeSimulationState_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.SimulationState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setPersonCount(int? count) => super.noSuchMethod(
        Invocation.method(
          #setPersonCount,
          [count],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSimulation(
    bool? value, {
    double? lat,
    double? lon,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleSimulation,
          [value],
          {
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i2.SimulationState? old,
    _i2.SimulationState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.RemoveListener addListener(
    _i6.Listener<_i2.SimulationState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i5.RemoveListener);
}
